### POST creacion de publicaciones
@tipoPublicacion1 = OFERTA
@token1 = eyJhbGciOiJIUzI1NiJ9.eyJVc2VySWQiOjIsInN1YiI6ImpvaG5kb2U0IiwiaWF0IjoxNzQ4MTE0MjY3LCJleHAiOjE3NDgyMDA2Njd9.1ua94y2TJWvcUNNfdgT_x5eDDIsOw8vY5qXmXnpvwos
@token2 = eyJhbGciOiJIUzI1NiJ9.eyJVc2VySWQiOjEsInN1YiI6ImpvaG5kb2UzIiwiaWF0IjoxNzQ4MTE0MjI5LCJleHAiOjE3NDgyMDA2Mjl9.hx3tUC6ACizAwnX6aFTJSOywLOjkxQ1YIl-kcleqB7c
POST http://localhost:9595/api/v1/publicaciones?tipoPublicacion={{tipoPublicacion1}}
Content-Type: application/json
Authorization: Bearer {{token1}}

{
  "titulo": "Titulo de ejemplo",
  "descripcion": "Descripción de la publicación",
  "tipoPublicacion": "OFERTA",
  "categoriaServicio": "TECNOLOGIA",
  "zonaId": 1
}

###
@id = 1
PUT http://localhost:9595/api/v1/publicaciones/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "titulo": "Titulo de ejemplo",
  "descripcion": "Descripción de la publicación3",
  "tipoPublicacion": "OFERTA",
  "categoriaServicio": "TECNOLOGIA",
  "zonaId": 1
}

###
@id1 = variable value
GET http://localhost:9595/api/v1/publicaciones/{{id1}}

###
GET http://localhost:9595/api/v1/publicaciones
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:9595/api/v1/publicaciones?tipoPublicacion={{tipoPublicacion2}}
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST http://localhost:9595/api/v1/publicaciones/{{id}}/reportar
Content-Type: application/json
Authorization: Bearer {{token2}}

###
GET http://localhost:9595/api/v1/publicaciones/mis-publicaciones
Content-Type: application/json
Authorization: Bearer {{token1}}

###
@idRepor = 5
POST http://localhost:9595/api/v1/publicaciones/{{idRepor}}/reportar
Content-Type: application/json
Authorization: Bearer {{token1}}

{
  "motivo": "Contenido inapropiado"
}

###
@id3 = variable value
POST http://localhost:9595/api/v1/publicaciones/{{id3}}/cancelar

###
@id4 = variable value
POST http://localhost:9595/api/v1/publicaciones/{{id4}}/finalizar
