###
GET http://localhost:9595/api/v1/zonas

###
@token = eyJhbGciOiJIUzI1NiJ9.eyJVc2VySWQiOjIsInN1YiI6ImpvaG5kb2U0IiwiaWF0IjoxNzQ4MTE0MjY3LCJleHAiOjE3NDgyMDA2Njd9.1ua94y2TJWvcUNNfdgT_x5eDDIsOw8vY5qXmXnpvwos
POST http://localhost:9595/api/v1/zonas
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "corregimiento": "Santa Rosa",
  "municipio": "Jamundí",
  "ciudad": "Cali",
  "departamento": "Valle del Cauca",
  "pais": "Colombia"
}

###
GET http://localhost:9595/api/v1/zonas/{{id}}

###
PUT http://localhost:9595/api/v1/zonas/{{id}}

###
DELETE http://localhost:9595/api/v1/zonas/{{id}}