server:
  port: 9595

spring:
  application.name: solveit
  threads.virtual.enabled: true

  datasource:
    url: jdbc:sqlserver://solveit-app.database.windows.net:1433;database=solveitdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
    username: adminsolveit@solveit-app
    password: Solveit2025*
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  mail:
    password: jnqo oafz cjjj grlp
    username: smtp.gmail.com

  jwt:
    origin:
      local: http://localhost:8081
      expo: https://solveit--u61lphwrdd.expo.app/
      prod: https://solveit.expo.app
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000




  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        jdbc:
          lob:
            non_contextual_creation: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include:
          - loggers
          - metrics
          - health
          - info

