server:
  port: 9595

spring:
  application.name: solveit

  threads.virtual.enabled: true
  jpa:
    generate-ddl: true

  datasource:
    url: localhost:3306
    username: myuser
    password: verysecret
    driver-class-name: com.mysql.cj.jdbc.Driver


management:
  endpoints:
    web:
      exposure:
        include:
          loggers,
          metrics,
          health,
          info