name: Dependency Check

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run dependency check
      run: |
        ./gradlew dependencies > dependencies.txt
        
    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'SolveIt'
        path: '.'
        format: 'HTML'
        out: 'reports'
        
    - name: Upload dependency check report
      uses: actions/upload-artifact@v3
      with:
        name: Dependency Check Report
        path: reports
        
    - name: GitHub Security Dashboard Report
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'SolveIt'
        path: '.'
        format: 'SARIF'
        out: 'reports'
        
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: reports/dependency-check-report.sarif